# Generated by Django 4.1 on 2022-08-31 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avtomobil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('yil', models.IntegerField()),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='avto_rasmlar')),
                ('manzil', models.CharField(max_length=200)),
                ('probeg', models.IntegerField()),
                ('kuzov', models.CharField(max_length=200)),
                ('dvigatel', models.CharField(max_length=200)),
                ('rang', models.CharField(max_length=200)),
                ('narx', models.IntegerField()),
                ('tel_nomer', models.IntegerField()),
                ('xarakteristika', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Avtomobil',
                'verbose_name_plural': 'Avtomobillar',
            },
        ),
    ]
